version: '0.2'
language: en
ignorePaths:
  - .vscode/**
  - node_modules/**
  - .pnpm-store/**
  - .svelte-kit/**
  - dist
  - build/**
  - dist/**
  - '**/*.d.ts'
  - '**/*.map'
  - '**/*.min.js'
  - '**/*.svg'
  - .git/**/*
  - .gitignore
  - package.json
  - pnpm-lock.yaml
words:
  - lefthook
  - libsql
  - Qube
  - sonarqube
  - Turso
  - Vite
