# sonar-project.properties
sonar.projectKey=dorayaki15 
sonar.projectName=quiz-game
sonar.organization=dorayaki15

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/*.spec.js,src/**/*.test.js,src/**/*.svelte.spec.ts,src/**/*.svelte.test.ts
sonar.exclusions=.svelte-kit/**,build/**,node_modules/**,static/**,.netlify/**,.wrangler/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
